/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as DietRouteImport } from './routes/diet'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as MembersIdRouteImport } from './routes/members.$id'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/diet': typeof DietRoute
  '/notices': typeof NoticesRoute
  '/payments': typeof PaymentsRoute
  '/plans': typeof PlansRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/trainers': typeof TrainersRoute
  '/workouts': typeof WorkoutsRoute
  '/members/$id': typeof MembersIdRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/diet': typeof DietRoute
  '/notices': typeof NoticesRoute
  '/payments': typeof PaymentsRoute
  '/plans': typeof PlansRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/trainers': typeof TrainersRoute
  '/workouts': typeof WorkoutsRoute
  '/members/$id': typeof MembersIdRoute
  '/members': typeof MembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/diet': typeof DietRoute
  '/notices': typeof NoticesRoute
  '/payments': typeof PaymentsRoute
  '/plans': typeof PlansRoute
  '/reports': typeof ReportsRoute
  '/revenue': typeof RevenueRoute
  '/settings': typeof SettingsRoute
  '/trainers': typeof TrainersRoute
  '/workouts': typeof WorkoutsRoute
  '/members/$id': typeof MembersIdRoute
  '/members/': typeof MembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/diet'
    | '/notices'
    | '/payments'
    | '/plans'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/trainers'
    | '/workouts'
    | '/members/$id'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/diet'
    | '/notices'
    | '/payments'
    | '/plans'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/trainers'
    | '/workouts'
    | '/members/$id'
    | '/members'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/diet'
    | '/notices'
    | '/payments'
    | '/plans'
    | '/reports'
    | '/revenue'
    | '/settings'
    | '/trainers'
    | '/workouts'
    | '/members/$id'
    | '/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  DietRoute: typeof DietRoute
  NoticesRoute: typeof NoticesRoute
  PaymentsRoute: typeof PaymentsRoute
  PlansRoute: typeof PlansRoute
  ReportsRoute: typeof ReportsRoute
  RevenueRoute: typeof RevenueRoute
  SettingsRoute: typeof SettingsRoute
  TrainersRoute: typeof TrainersRoute
  WorkoutsRoute: typeof WorkoutsRoute
  MembersIdRoute: typeof MembersIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  DietRoute: DietRoute,
  NoticesRoute: NoticesRoute,
  PaymentsRoute: PaymentsRoute,
  PlansRoute: PlansRoute,
  ReportsRoute: ReportsRoute,
  RevenueRoute: RevenueRoute,
  SettingsRoute: SettingsRoute,
  TrainersRoute: TrainersRoute,
  WorkoutsRoute: WorkoutsRoute,
  MembersIdRoute: MembersIdRoute,
  MembersIndexRoute: MembersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
